name: medhub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-190.0.dev <4.0.0"

dependencies:
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_feather_icons: ^2.0.0+1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  morphable_shape: ^1.6.6
  percent_indicator: ^4.2.3
  pinput: ^5.0.0
  shared_preferences: ^2.2.3
  timer_count_down: ^2.2.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
